# -*- coding: utf-8 -*-
"""working with sql / json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LqTIOxWK2cMma-aRnXkml-yF2piXebn
"""

import pandas as pd

pd.read_json('/content/drive/MyDrive/100 days of ML by campusX/iris.json') # Working with JSON

pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

!pip install mysql.connector #Download Xampp---> Apache: web server to host web pages, MySQL/MariaDB:database management system for storing application data, PHP:scripting language for server-side processing,Perl:optional component for scripting, phpMyAdmin:web-based interface for managing MySQL/MariaDB databases.

import mysql.connector #Go to http://localhost/phpmyadmin ----> create database for world.sql

conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

df #Working with sql